<?php

/**
 * Implements hook_entity_info_alter().
 */
function adhoc_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['page_list'] = array(
        'label' => t('Page list'),
        'custom settings' => TRUE,
    );
}

/**
 * Implements hook_preprocess_node().
 */
function adhoc_preprocess_node(&$variables) {
    if($variables['view_mode'] == 'page_list') {
        $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__page_list';
    }
}